// <auto-generated />
using System;
using EventosBackend.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EventosBackend.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20250506043237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EVENTOS")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventosBackend.Models.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDSALA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id")
                        .HasName("PK_RESERVAS");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("RESERVA", "EVENTOS");
                });

            modelBuilder.Entity("EventosBackend.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("APELLIDO1");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("APELLIDO2");

                    b.Property<byte[]>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("RAW(255)")
                        .HasColumnName("CONTRASENA_HASH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_NACIMIENTO");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_REGISTRO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("RAW(100)")
                        .HasColumnName("SALT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONO");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("CLIENTE")
                        .HasColumnName("TIPO_USUARIO");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_LOGIN");

                    b.HasKey("IdUsuario")
                        .HasName("PK_USUARIO");

                    b.ToTable("USUARIO", "EVENTOS");
                });

            modelBuilder.Entity("EventosBackend.Models.Entities.Reserva", b =>
                {
                    b.HasOne("EventosBackend.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RESERVA_USUARIO");

                    b.HasOne("EventosBackend.Models.Entities.Usuario", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EventosBackend.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
