// <auto-generated />
using System;
using EventosBackend.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EventosBackend.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EVENTOS")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventosBackend.Models.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDSALA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDUSUARIO");

                    b.HasKey("Id")
                        .HasName("PK_RESERVAS");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RESERVA", "EVENTOS");
                });

            modelBuilder.Entity("EventosBackend.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("APELLIDO1");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("APELLIDO2");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("CONTRASENA_HASH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_NACIMIENTO");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_REGISTRO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SALT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONO");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("CLIENTE")
                        .HasColumnName("TIPO_USUARIO");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_LOGIN");

                    b.HasKey("IdUsuario")
                        .HasName("PK_USUARIO");

                    b.ToTable("USUARIO", "EVENTOS");
                });

            modelBuilder.Entity("SALA", b =>
                {
                    b.Property<int>("IdSALA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SALA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSALA"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACIDAD");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRIPCION_CORTA");

                    b.Property<int?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("DESCUENTO");

                    b.Property<string>("DetallesPago")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DETALLES_PAGO");

                    b.Property<int?>("Espacio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESPACIO");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("DISPONIBLE")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Horario")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("HORARIO");

                    b.Property<string>("ImagenPrincipal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("IMAGEN_PRINCIPAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal?>("PrecioAlta")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO_ALTA");

                    b.Property<decimal?>("PrecioBaja")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO_BAJA");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO_BASE");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("UBICACION");

                    b.HasKey("IdSALA")
                        .HasName("PK_SALA");

                    b.ToTable("SALA", "EVENTOS");
                });

            modelBuilder.Entity("SALA_CATERING", b =>
                {
                    b.Property<int>("IdCatering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATERING");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCatering"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SALA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdCatering")
                        .HasName("PK_SALA_CATERING");

                    b.HasIndex("IdSala")
                        .HasDatabaseName("IX_SALA_CATERING_ID_SALA");

                    b.ToTable("SALA_CATERING", "EVENTOS");
                });

            modelBuilder.Entity("SALA_EQUIPAMIENTO", b =>
                {
                    b.Property<int>("IdEquipamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EQUIPAMIENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamiento"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("CANTIDAD");

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SALA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdEquipamiento")
                        .HasName("PK_SALA_EQUIPAMIENTO");

                    b.HasIndex("IdSala")
                        .HasDatabaseName("IX_SALA_EQUIPAMIENTO_ID_SALA");

                    b.ToTable("SALA_EQUIPAMIENTO", "EVENTOS");
                });

            modelBuilder.Entity("SALA_EVENTO", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EVENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SALA");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMBRE_EVENTO");

                    b.HasKey("IdEvento")
                        .HasName("PK_SALA_EVENTO");

                    b.HasIndex("IdSala")
                        .HasDatabaseName("IX_SALA_EVENTO_ID_SALA");

                    b.ToTable("SALA_EVENTO", "EVENTOS");
                });

            modelBuilder.Entity("SALA_GALERIA", b =>
                {
                    b.Property<int>("IdGaleria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_GALERIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGaleria"));

                    b.Property<int>("IdSala")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SALA");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("ORDEN");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("URL_IMAGEN");

                    b.HasKey("IdGaleria")
                        .HasName("PK_SALA_GALERIA");

                    b.HasIndex("IdSala")
                        .HasDatabaseName("IX_SALA_GALERIA_ID_SALA");

                    b.ToTable("SALA_GALERIA", "EVENTOS");
                });

            modelBuilder.Entity("EventosBackend.Models.Entities.Reserva", b =>
                {
                    b.HasOne("EventosBackend.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RESERVA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SALA_CATERING", b =>
                {
                    b.HasOne("SALA", "Sala")
                        .WithMany("Catering")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CATERING_SALA");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("SALA_EQUIPAMIENTO", b =>
                {
                    b.HasOne("SALA", "Sala")
                        .WithMany("Equipamiento")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EQUIPAMIENTO_SALA");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("SALA_EVENTO", b =>
                {
                    b.HasOne("SALA", "Sala")
                        .WithMany("Eventos")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EVENTO_SALA");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("SALA_GALERIA", b =>
                {
                    b.HasOne("SALA", "Sala")
                        .WithMany("Galeria")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GALERIA_SALA");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("SALA", b =>
                {
                    b.Navigation("Catering");

                    b.Navigation("Equipamiento");

                    b.Navigation("Eventos");

                    b.Navigation("Galeria");
                });
#pragma warning restore 612, 618
        }
    }
}
